version: '3.9'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    links:
      - db
  
  photogram:
    build: "photogram/."
    restart: always
    ports:
    # want to add ports
      - 1234:1234 
    volumes:
      - userdata:/root
      - ./photogram/php-class-project:/var/www/html
    links:
      - adminer
      - db

volumes:
  userdata: